mysql:
  image: mysql:5
  ports:
    - "3308:3306"
  environment:
    MYSQL_PASSWORD: samplepassw
    MYSQL_USER: sampleuser
    MYSQL_DATABASE: sampledb
    MYSQL_ROOT_PASSWORD: rootpassw
  volumes:
    - .:/docker-entrypoint-initdb.d
